/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import javax.swing.JOptionPane;
import modelo.Traductor;
import modelo.Usuario;

/**
 *
 * @author Richard Vanegas - Andres Ciro
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private Traductor miTraductor;

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        jPRecuperar.setVisible(false);
        jPCambiarContraseña.setVisible(false);
        try {
            miTraductor = new Traductor();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "No se ha podido leer el archivo"
                    + " para cargar el listado de personas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jTBPrincipal = new javax.swing.JTabbedPane();
        jPRegistroPalabra = new javax.swing.JPanel();
        jPLoginUsuario = new javax.swing.JPanel();
        jLNombreUsuarioLogin = new javax.swing.JLabel();
        jLContraseñaLogin = new javax.swing.JLabel();
        jTFNombreUsuarioLogin = new javax.swing.JTextField();
        jBLogin = new javax.swing.JButton();
        jBRecuperar = new javax.swing.JButton();
        jPFContraseñaLogin = new javax.swing.JPasswordField();
        jPRecuperar = new javax.swing.JPanel();
        jLNombreUsuarioRecuperar = new javax.swing.JLabel();
        jPPreguntaRespuesta = new javax.swing.JPanel();
        jLPreguntaRecuperar = new javax.swing.JLabel();
        jTFRespuestaRecuperar = new javax.swing.JTextField();
        jPCambiarContraseña = new javax.swing.JPanel();
        jLIngreseContraseña = new javax.swing.JLabel();
        jTFNuevaContraseña = new javax.swing.JTextField();
        jBCambiarContraseña = new javax.swing.JButton();
        jBResponder = new javax.swing.JButton();
        jTFNombreUsuarioRecuperar = new javax.swing.JTextField();
        jPRegistroUsuario = new javax.swing.JPanel();
        jPDatosUsuario = new javax.swing.JPanel();
        jLNombreUsuario = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLGenero = new javax.swing.JLabel();
        jLPreguntaSeg = new javax.swing.JLabel();
        jLRespuestaSeg = new javax.swing.JLabel();
        jTFNombreUsuario = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFRespuestaSeg = new javax.swing.JTextField();
        jBRegistrarUsuario = new javax.swing.JButton();
        jCBGenero = new javax.swing.JComboBox<>();
        jCBPreguntaSeguridad = new javax.swing.JComboBox<>();
        jPFContrasenia = new javax.swing.JPasswordField();
        jLEncabezado = new javax.swing.JLabel();
        jLEslogan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLTitulo.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(153, 0, 0));
        jLTitulo.setText("TRADUCTOR CIVA");

        jTBPrincipal.setBackground(new java.awt.Color(102, 204, 255));
        jTBPrincipal.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N

        jPRegistroPalabra.setBackground(new java.awt.Color(102, 204, 255));

        jPLoginUsuario.setBackground(new java.awt.Color(0, 153, 255));
        jPLoginUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Login de usuario"));

        jLNombreUsuarioLogin.setText("Nombre de usuario:");

        jLContraseñaLogin.setText("Contraseña:");

        jTFNombreUsuarioLogin.setBackground(new java.awt.Color(153, 204, 255));

        jBLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/login.png"))); // NOI18N
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jBRecuperar.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jBRecuperar.setForeground(new java.awt.Color(51, 153, 255));
        jBRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/olvidar.png"))); // NOI18N
        jBRecuperar.setText("¿Olvidó su contraseña?... Recuperela aquí!");
        jBRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecuperarActionPerformed(evt);
            }
        });

        jPFContraseñaLogin.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPLoginUsuarioLayout = new javax.swing.GroupLayout(jPLoginUsuario);
        jPLoginUsuario.setLayout(jPLoginUsuarioLayout);
        jPLoginUsuarioLayout.setHorizontalGroup(
            jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLNombreUsuarioLogin)
                .addGap(18, 18, 18)
                .addGroup(jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombreUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLoginUsuarioLayout.createSequentialGroup()
                        .addComponent(jLContraseñaLogin)
                        .addGap(33, 33, 33)
                        .addComponent(jPFContraseñaLogin))
                    .addComponent(jBRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPLoginUsuarioLayout.setVerticalGroup(
            jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreUsuarioLogin)
                    .addComponent(jLContraseñaLogin)
                    .addComponent(jTFNombreUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFContraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPLoginUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPRecuperar.setBackground(new java.awt.Color(0, 153, 255));
        jPRecuperar.setBorder(javax.swing.BorderFactory.createTitledBorder("Recuperar contraseña"));

        jLNombreUsuarioRecuperar.setText("Nombre de usuario:");

        jPPreguntaRespuesta.setBackground(new java.awt.Color(51, 102, 255));
        jPPreguntaRespuesta.setBorder(javax.swing.BorderFactory.createTitledBorder("Responda la pregunta de seguridad"));

        jTFRespuestaRecuperar.setBackground(new java.awt.Color(153, 204, 255));

        jPCambiarContraseña.setBackground(new java.awt.Color(51, 102, 255));
        jPCambiarContraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLIngreseContraseña.setText("Ingrese su nueva contraseña:");

        jTFNuevaContraseña.setBackground(new java.awt.Color(153, 204, 255));

        jBCambiarContraseña.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jBCambiarContraseña.setForeground(new java.awt.Color(51, 153, 255));
        jBCambiarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/cambiarPass.png"))); // NOI18N
        jBCambiarContraseña.setText("CAMBIAR CONTRASEÑA");
        jBCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCambiarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCambiarContraseñaLayout = new javax.swing.GroupLayout(jPCambiarContraseña);
        jPCambiarContraseña.setLayout(jPCambiarContraseñaLayout);
        jPCambiarContraseñaLayout.setHorizontalGroup(
            jPCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCambiarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIngreseContraseña)
                .addGap(18, 18, 18)
                .addComponent(jTFNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jBCambiarContraseña)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCambiarContraseñaLayout.setVerticalGroup(
            jPCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCambiarContraseñaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIngreseContraseña)
                    .addComponent(jTFNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCambiarContraseña))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jBResponder.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jBResponder.setForeground(new java.awt.Color(51, 153, 255));
        jBResponder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/responder.png"))); // NOI18N
        jBResponder.setText("RESPONDER");
        jBResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResponderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPreguntaRespuestaLayout = new javax.swing.GroupLayout(jPPreguntaRespuesta);
        jPPreguntaRespuesta.setLayout(jPPreguntaRespuestaLayout);
        jPPreguntaRespuestaLayout.setHorizontalGroup(
            jPPreguntaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreguntaRespuestaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPPreguntaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPreguntaRespuestaLayout.createSequentialGroup()
                        .addGroup(jPPreguntaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPreguntaRecuperar)
                            .addComponent(jPCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPPreguntaRespuestaLayout.createSequentialGroup()
                        .addComponent(jTFRespuestaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBResponder)
                        .addGap(63, 63, 63))))
        );
        jPPreguntaRespuestaLayout.setVerticalGroup(
            jPPreguntaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPreguntaRespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPreguntaRecuperar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPreguntaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRespuestaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBResponder))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTFNombreUsuarioRecuperar.setBackground(new java.awt.Color(153, 204, 255));
        jTFNombreUsuarioRecuperar.setEnabled(false);

        javax.swing.GroupLayout jPRecuperarLayout = new javax.swing.GroupLayout(jPRecuperar);
        jPRecuperar.setLayout(jPRecuperarLayout);
        jPRecuperarLayout.setHorizontalGroup(
            jPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRecuperarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRecuperarLayout.createSequentialGroup()
                        .addComponent(jLNombreUsuarioRecuperar)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNombreUsuarioRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRecuperarLayout.createSequentialGroup()
                        .addComponent(jPPreguntaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPRecuperarLayout.setVerticalGroup(
            jPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRecuperarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreUsuarioRecuperar)
                    .addComponent(jTFNombreUsuarioRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPPreguntaRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPRegistroPalabraLayout = new javax.swing.GroupLayout(jPRegistroPalabra);
        jPRegistroPalabra.setLayout(jPRegistroPalabraLayout);
        jPRegistroPalabraLayout.setHorizontalGroup(
            jPRegistroPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroPalabraLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPRegistroPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroPalabraLayout.createSequentialGroup()
                        .addComponent(jPRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPRegistroPalabraLayout.setVerticalGroup(
            jPRegistroPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroPalabraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTBPrincipal.addTab("LogIn", jPRegistroPalabra);

        jPRegistroUsuario.setBackground(new java.awt.Color(51, 204, 255));

        jPDatosUsuario.setBackground(new java.awt.Color(51, 153, 255));
        jPDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        jLNombreUsuario.setText("Nombre de usuario:");

        jLContraseña.setText("Contraseña:");

        jLNombre.setText("Nombre:");

        jLApellido.setText("Apellido:");

        jLEmail.setText("E-mail:");

        jLGenero.setText("Genero:");

        jLPreguntaSeg.setText("Pregunta de seguridad:");

        jLRespuestaSeg.setText("Respuesta de seguridad:");

        jTFNombreUsuario.setBackground(new java.awt.Color(153, 204, 255));

        jTFNombre.setBackground(new java.awt.Color(153, 204, 255));

        jTFApellido.setBackground(new java.awt.Color(153, 204, 255));

        jTFEmail.setBackground(new java.awt.Color(153, 204, 255));

        jTFRespuestaSeg.setBackground(new java.awt.Color(153, 204, 255));

        jBRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/save.png"))); // NOI18N
        jBRegistrarUsuario.setText("Registrar Usuario");
        jBRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarUsuarioActionPerformed(evt);
            }
        });

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su genero", "Femenino", "Masculino" }));

        jCBPreguntaSeguridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la pregunta de seguridad", "¿ Lugar de nacimiento de tu madre ?", "¿ Nombre de tu profesor favorito ?", "¿ Nombre de tu primera mascota ?", "¿ Ocupacion de tu abuelo ?" }));

        jPFContrasenia.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPDatosUsuarioLayout = new javax.swing.GroupLayout(jPDatosUsuario);
        jPDatosUsuario.setLayout(jPDatosUsuarioLayout);
        jPDatosUsuarioLayout.setHorizontalGroup(
            jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                                .addComponent(jLRespuestaSeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jTFRespuestaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                                .addComponent(jLApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                                .addComponent(jLNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosUsuarioLayout.createSequentialGroup()
                                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLEmail)
                                    .addComponent(jLGenero)
                                    .addComponent(jLPreguntaSeg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jCBGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBPreguntaSeguridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombreUsuario)
                                    .addComponent(jLContraseña))
                                .addGap(118, 118, 118)
                                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jPFContrasenia))))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBRegistrarUsuario)
                        .addGap(186, 186, 186))))
        );
        jPDatosUsuarioLayout.setVerticalGroup(
            jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreUsuario)
                    .addComponent(jTFNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContraseña)
                    .addComponent(jPFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGenero)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPreguntaSeg)
                    .addComponent(jCBPreguntaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRespuestaSeg)
                    .addComponent(jTFRespuestaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jBRegistrarUsuario)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPRegistroUsuarioLayout = new javax.swing.GroupLayout(jPRegistroUsuario);
        jPRegistroUsuario.setLayout(jPRegistroUsuarioLayout);
        jPRegistroUsuarioLayout.setHorizontalGroup(
            jPRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroUsuarioLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPRegistroUsuarioLayout.setVerticalGroup(
            jPRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTBPrincipal.addTab("Registro de Usuario", jPRegistroUsuario);

        jLEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/encabezado.jpg"))); // NOI18N

        jLEslogan.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        jLEslogan.setText("La mejor traduccion para tu necesidad...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTBPrincipal)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLEncabezado)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLTitulo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLEslogan)
                                .addGap(31, 31, 31))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEslogan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        String nomUsuario = jTFNombreUsuario.getText();
        char password[] = jPFContrasenia.getPassword();
        String contrasenia = "";
        for (int i = 0; i < password.length; i++) {
            contrasenia += ((Character) password[i]).toString();
        }
        String nombre = jTFNombre.getText();
        String apellido = jTFApellido.getText();
        String email = jTFEmail.getText();
        String genero = (String) jCBGenero.getSelectedItem();
        String preguntaSeg = (String) jCBPreguntaSeguridad.getSelectedItem();
        String respuestaSeg = jTFRespuestaSeg.getText();
        if (nomUsuario.isEmpty() || contrasenia.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || email.isEmpty()
                || jCBGenero.getSelectedIndex() == 0 || jCBPreguntaSeguridad.getSelectedIndex() == 0 || respuestaSeg.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los datos");
        } else if (contrasenia.length() < 8) {
            JOptionPane.showMessageDialog(null, "La contraseña debe ser minimo de 8 caracteres");
        } else if (!validarContraseña(contrasenia)) {
            JOptionPane.showMessageDialog(null, "La contraseña debe tener almenos una letra y un numero");
        } else {

            Usuario u = new Usuario(nombre, apellido, email, genero, nomUsuario, contrasenia, preguntaSeg, respuestaSeg);
            boolean msj = miTraductor.registrarUsuario(u);
            if (msj == true) {
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
                limpiarCamposRegistro();
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con este nickname");
            }
        }

    }//GEN-LAST:event_jBRegistrarUsuarioActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        // TODO add your handling code here:
        String nomUsuario = jTFNombreUsuarioLogin.getText();
        String contraseña = jPFContraseñaLogin.getText();
        Usuario usu = miTraductor.validarLogin(nomUsuario, contraseña);
        if (usu != null) {
            DiccionarioTraductor ventanaDiccionario = new DiccionarioTraductor(miTraductor, usu);
            ventanaDiccionario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "El usuario o la contraseña no coinciden "
                    + "con los registros de nuestra base de datos");
        }

    }//GEN-LAST:event_jBLoginActionPerformed

    public boolean validarContraseña(String pass) {
        boolean tieneLetra = false;
        boolean tieneNumero = false;
        for (int i = 0; i < pass.length(); i++) {
            char letra = pass.charAt(i);
            if (Character.isDigit(letra)) {
                tieneNumero = true;
            }
            if (Character.isLetter(letra)) {
                tieneLetra = true;
            }
        }
        return tieneLetra == true && tieneNumero == true;
    }
    private void jBRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecuperarActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Ingrese su nombre de usuario");
        Usuario u = miTraductor.buscarUsuario(nombre);
        if (u != null) {
            jPRecuperar.setVisible(true);
            jTFNombreUsuarioRecuperar.setText(nombre);
            jLPreguntaRecuperar.setText(u.getPreguntaSeg());
        } else {
            JOptionPane.showMessageDialog(null, "Este usuario no se encuentra registrado");
        }
    }//GEN-LAST:event_jBRecuperarActionPerformed

    private void jBResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResponderActionPerformed
        // TODO add your handling code here:
        Usuario u = miTraductor.buscarUsuario(jTFNombreUsuarioRecuperar.getText());
        String respuesta = jTFRespuestaRecuperar.getText();
        if (u.getRespuestaSeg().equalsIgnoreCase(respuesta)) {
            jPCambiarContraseña.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
        }
    }//GEN-LAST:event_jBResponderActionPerformed

    private void jBCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        String contraseña = jTFNuevaContraseña.getText();
        Usuario u = miTraductor.buscarUsuario(jTFNombreUsuarioRecuperar.getText());
        if (contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar su nueva contraseña");
        } else if (contraseña.length() < 8) {
            JOptionPane.showMessageDialog(null, "La contraseña debe ser minimo de 8 caracteres");
        } else {
            u.setContraseña(contraseña);
            JOptionPane.showMessageDialog(null, "Se cambio correctamente la contraseña");
            limpiarCamposRecuperar();
        }

    }//GEN-LAST:event_jBCambiarContraseñaActionPerformed

    //Limpia los campos del formulario de recuperar contraseña
    public void limpiarCamposRecuperar() {
        jTFNombreUsuarioRecuperar.setText(null);
        jTFRespuestaRecuperar.setText(null);
        jTFNuevaContraseña.setText(null);
        jPRecuperar.setVisible(false);
    }

    //Limpia los campos del formulario de registro de usuarios
    public void limpiarCamposRegistro() {
        jTFNombreUsuario.setText(null);
        jPFContrasenia.setText(null);
        jTFNombre.setText(null);
        jTFApellido.setText(null);
        jTFEmail.setText(null);
        jCBGenero.setSelectedIndex(0);
        jCBPreguntaSeguridad.setSelectedIndex(0);
        jTFRespuestaSeg.setText(null);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCambiarContraseña;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBRecuperar;
    private javax.swing.JButton jBRegistrarUsuario;
    private javax.swing.JButton jBResponder;
    private javax.swing.JComboBox<String> jCBGenero;
    private javax.swing.JComboBox<String> jCBPreguntaSeguridad;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLContraseñaLogin;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEncabezado;
    private javax.swing.JLabel jLEslogan;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIngreseContraseña;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombreUsuario;
    private javax.swing.JLabel jLNombreUsuarioLogin;
    private javax.swing.JLabel jLNombreUsuarioRecuperar;
    private javax.swing.JLabel jLPreguntaRecuperar;
    private javax.swing.JLabel jLPreguntaSeg;
    private javax.swing.JLabel jLRespuestaSeg;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPCambiarContraseña;
    private javax.swing.JPanel jPDatosUsuario;
    private javax.swing.JPasswordField jPFContrasenia;
    private javax.swing.JPasswordField jPFContraseñaLogin;
    private javax.swing.JPanel jPLoginUsuario;
    private javax.swing.JPanel jPPreguntaRespuesta;
    private javax.swing.JPanel jPRecuperar;
    private javax.swing.JPanel jPRegistroPalabra;
    private javax.swing.JPanel jPRegistroUsuario;
    private javax.swing.JTabbedPane jTBPrincipal;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombreUsuario;
    private javax.swing.JTextField jTFNombreUsuarioLogin;
    private javax.swing.JTextField jTFNombreUsuarioRecuperar;
    private javax.swing.JTextField jTFNuevaContraseña;
    private javax.swing.JTextField jTFRespuestaRecuperar;
    private javax.swing.JTextField jTFRespuestaSeg;
    // End of variables declaration//GEN-END:variables
}
